name: "Scheduled tasks"
on:
  schedule:
    - cron: "0 0 * * 1,3,5" # midnight on Monday, Wednesday, Friday

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This pull request has not had any activity recently. It will be closed without further activity."

          days-before-stale: 14
          days-before-close: 7

          stale-pr-label: "C-stale"
          exempt-pr-labels: "C-keep-open"

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Audit dependencies
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
